# Clase 11
### Webscrapping

In [1]:
import seaborn as sns

import seaborn.objects as so
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

In [6]:
pip install mkl numpy seaborn

Defaulting to user installation because normal site-packages is not writeable
Collecting mkl
  Using cached mkl-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: numpy in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (2.2.4)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting intel-openmp<2026,>=2024 (from mkl)
  Using cached intel_openmp-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Collecting tbb==2022.* (from mkl)
  Using cached tbb-2022.1.0-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (1.0 kB)
Collecting tcmlib==1.* (from tbb==2022.*->mkl)
  Using cached tcmlib-1.3.0-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (964 bytes)
Requirement already satisfied: pandas>=1.2 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from seaborn) (3.10.1)
Collecting intel-cmplr-lib-ur==2025.1.0 (from intel-openmp<2026,>=2024->mkl)
  Using cached intel_cmplr_lib_ur-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Collecting umf==0.10.* (from intel-cmplr-lib-ur==2025.1.0->intel-openmp<2026,>=2024->mkl)
  Using cached umf-0.10.0-py2.py3-none-manylinux_2_28_x86_64.whl.metadata (1.0 kB)
Requirement already satisfied: contourpy>=1.0.1 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/envs/m2/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached mkl-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (186.8 MB)
Using cached tbb-2022.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (3.6 MB)
Using cached tcmlib-1.3.0-py2.py3-none-manylinux_2_28_x86_64.whl (4.2 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached intel_openmp-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (48.6 MB)
Downloading intel_cmplr_lib_ur-2025.1.0-py2.py3-none-manylinux_2_28_x86_64.whl (26.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.3/26.3 MB 1.1 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading umf-0.10.0-py2.py3-none-manylinux_2_28_x86_64.whl (314 kB)
Installing collected packages: tcmlib, umf, tbb, intel-cmplr-lib-ur, seaborn, intel-openmp, mkl
Successfully installed intel-cmplr-lib-ur-2025.1.0 intel-openmp-2025.1.0 mkl-2025.1.0 seaborn-0.13.2 tbb-2022.1.0 tcmlib-1.3.0 umf-0.10.0
Note: you may need to restart the kernel to use updated packages.

En este trabajo exploraremos la base de datos `Sleep_Efficiency_Cleaning.csv`. Es una base descargada de kaggle.com generada a partir de información sobre los hábitos de sueño de distintas personas. La base está levemente modificada para los ejercicios de este trabajo. Las variables incluidas son:

- **ID:** identificación de participante
- **Age:** edad
- **Gender:** que designa al género de cada persona
- **Bedtime:** que tiene la hora a la que se va a dormir la persona
- **Wakeup time:** que tiene la hora a la que se despiertan las personas
- **Sleep.duration:**  que nos dice cuánto tiempo pasa cada persona durmiendo
- **Sleep.efficiency:** que nos dice cuanto del tiempo que pasan laa persona en la cama, efectivamente duermen.
- **REM sleep percentage:**  que tiene la proporción de sueño REM de la persona
- **Deep sleep percentage:**  que tiene la proporción de sueño profundo de la persona
- **Light sleep percentage:**  que tiene la proporción de sueño liviano de la persona
- **Awakenings:** que tiene la cantidad de veces que la persona se despierta a la noche
- **Caffeine consumption:** que nos dice la cantidad de cafeina que consume la persona
- **Alcohol consumption:** que nos dice la cantidad de alcohol que consume la persona
- **Smoking.status:** que nos dice si la persona es o no es fumadora
- **Excersice frequency:** que nos dice cuán frecuentemente hace ejercicio la persona

In [8]:
datos = pd.read_csv("/home/Estudiante/Descargas/Sleep_efficiency_cleaning.csv")
datos

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [28]:
nuevos_datos = (datos["Sleep duration"] >= 6.0 )& (datos["Age"]>=17)
nuevos_datos

0      True
1      True
2      True
3      True
4      True
       ...
457    True
458    True
459    True
460    True
461    True
Length: 462, dtype: bool

In [29]:
datos[nuevos_datos]

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

nuevos_datos.value_counts().plot() == me muestra un grafico aunq totalmente inentendible e incompleto

#### 1. Con lo que sabemos hasta ahora, tomemonos 10 minutos para chusmear los datos

¿Les parece que podría haber cosas para limpiar en los datos? ¿Por qué?

### 2. Limpieza de los datos

Nos interesará realizar algunas acciones de limpieza de datos:
- Filtrar datos
- Renombrar variables
- Eliminar datos faltantes
- Eliminar duplicados
- Filtrar datos

#### 2.a. Filtrado

### 2.b. Renombrar variables con diccionarios

Como vimos, nuestra base de datos tiene nombres de variables en ingles. Pero como nosotros somos más argentinos que usar ojotas con medias, vamos a pasarlo al castellano.

Para eso, nos van a servir mucho los **diccionarios**, que se utilizan para almacenar valores de datos en pares clave:valor.

Un diccionario es una colección ordenada, modificable y que no permite duplicados.

Yo podría generar este diccionario llamado dict

In [32]:
# Ejemplo
dict = { "hola" : "Expresión de saludo utilizada entre dos o más personas de trato familiar", "cinco" : 5, "dias" : ["lunes", "martes", "miercoles"]}

Si le pregunto que significa "hola", me dirá:

In [33]:
dict["hola"]

'Expresión de saludo utilizada entre dos o más personas de trato familiar'

Para lo que nos interesa a nosotros, podríamos tener lo siguiente:

In [43]:
nombres = {
  "ID": "ID",
  "Age": "Edad",
  "Gender": "Género",
  "Bedtime": "Hora dormir",
  "Wakeup time": "Hora despertar",
  "Sleep.duration": "Duracion suenio",
  "Sleep.efficiency": "Eficiencia suenio",
  "REM sleep percentage": "Porcentaje suenio REM",
  "Deep sleep percentage": "Porcentaje suenio profundo",
  "Light sleep percentage": "Porcentaje suenio liviano",
  "Awakenings": "Despertares",
  "Caffeine consumption": "Consumo cafeina",
  "Alcohol consumption": "Consumo alcohol",
  "Smoking status": "Fumador",
  "Exercise frequency": "Frecuencia ejercicio"
}

Para cambiar los nombres deberíamos usar rename() ¿Cómo lo usarian?

Pueden chusmear la ayuda

In [171]:
help(pd.DataFrame.rename)

Help on function rename in module pandas.core.frame:

rename(self, mapper: 'Renamer | None' = None, *, index: 'Renamer | None' = None, columns: 'Renamer | None' = None, axis: 'Axis | None' = None, copy: 'bool | None' = None, inplace: 'bool' = False, level: 'Level | None' = None, errors: 'IgnoreRaise' = 'ignore') -> 'DataFrame | None'
    Rename columns or index labels.

    Function / dict values must be unique (1-to-1). Labels not contained in
    a dict / Series will be left as-is. Extra labels listed don't throw an
    error.

    See the :ref:`user guide <basics.rename>` for more.

    Parameters
    ----------
    mapper : dict-like or function
        Dict-like or function transformations to apply to
        that axis' values. Use either ``mapper`` and ``axis`` to
        specify the axis to target with ``mapper``, or ``index`` and
        ``columns``.
    index : dict-like or function
        Alternative to specifying axis (``mapper, axis=0``
        is equivalent to ``index=mapper``).
    columns : dict-like or function
        Alternative to specifying axis (``mapper, axis=1``
        is equivalent to ``columns=mapper``).
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis to target with ``mapper``. Can be either the axis name
        ('index', 'columns') or number (0, 1). The default is 'index'.
    copy : bool, default True
        Also copy underlying data.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
        If True then value of copy is ignored.
    level : int or level name, default None
        In case of a MultiIndex, only rename labels in the specified
        level.
    errors : {'ignore', 'raise'}, default 'ignore'
        If 'raise', raise a `KeyError` when a dict-like `mapper`, `index`,
        or `columns` contains labels that are not present in the Index
        being transformed.
        If 'ignore', existing keys will be renamed and extra keys will be
        ignored.

    Returns
    -------
    DataFrame or None
        DataFrame with the renamed axis labels or None if ``inplace=True``.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis and
        "errors='raise'".

    See Also
    --------
    DataFrame.rename_axis : Set the name of the axis.

    Examples
    --------
    ``DataFrame.rename`` supports two calling conventions

    * ``(index=index_mapper, columns=columns_mapper, ...)``
    * ``(mapper, axis={'index', 'columns'}, ...)``

    We *highly* recommend using keyword arguments to clarify your
    intent.

    Rename columns using a mapping:

    >>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
    >>> df.rename(columns={"A": "a", "B": "c"})
       a  c
    0  1  4
    1  2  5
    2  3  6

    Rename index using a mapping:

    >>> df.rename(index={0: "x", 1: "y", 2: "z"})
       A  B
    x  1  4
    y  2  5
    z  3  6

    Cast index labels to a different type:

    >>> df.index
    RangeIndex(start=0, stop=3, step=1)
    >>> df.rename(index=str).index
    Index(['0', '1', '2'], dtype='object')

    >>> df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")
    Traceback (most recent call last):
    KeyError: ['C'] not found in axis

    Using axis-style parameters:

    >>> df.rename(str.lower, axis='columns')
       a  b
    0  1  4
    1  2  5
    2  3  6

    >>> df.rename({1: 2, 2: 4}, axis='index')
       A  B
    0  1  4
    2  2  5
    4  3  6

In [41]:
datos = datos.rename(columns = nombres)
datos

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Despertares,Consumo cafeina,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

Quiero escribir todo ahora en mayuscula.

In [44]:
datos.rename (columns = str.upper)

,ID,EDAD,GÉNERO,HORA DORMIR,HORA DESPERTAR,SLEEP DURATION,SLEEP EFFICIENCY,PORCENTAJE SUENIO REM,PORCENTAJE SUENIO PROFUNDO,PORCENTAJE SUENIO LIVIANO,DESPERTARES,CONSUMO CAFEINA,CONSUMO ALCOHOL,FUMADOR,FRECUENCIA EJERCICIO
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

#### 2. c. Eliminar valores faltantes

¿Qué significa un valor perdido?

Los datos faltantes son algo típico de cualquier pipeline de análisis de datos. En general los paquetes estadísticos (pandas, dplyr, etc) tratan de facilitar el manejo de estos tipos de datos. En Pandas, se utiliza la expresión NaN (Not a number) o NA que viene del mundo R (Not available)

Para poder acceder a los datos faltantes, podemos utilizar la función isna() 

¿Cómo la usamos? ¿Qué nos devuelve?

datos.isna() pone en cada celda si es o no NA. Para poder ordenar la info y saber la cantidad de datos faltantes puedo usar sum para saber la cantidad de datos faltantes en cada columna.

In [46]:
datos.isna().sum()

ID                             0
Edad                           0
Género                         0
Hora dormir                    0
Hora despertar                 0
Sleep duration                 0
Sleep efficiency               0
Porcentaje suenio REM          0
Porcentaje suenio profundo     0
Porcentaje suenio liviano      0
Despertares                   20
Consumo cafeina               25
Consumo alcohol               15
Fumador                        0
Frecuencia ejercicio           6
dtype: int64

In [51]:
datos1 = datos.dropna()
datos1

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Despertares,Consumo cafeina,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

Para no sacar todos lo datos faltantes y perjudicar el dataset puedo usar un limitador de datos

In [55]:
datos.dropna(thresh = 14)

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Despertares,Consumo cafeina,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [56]:
datos.dropna(axis = "columns")

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Fumador
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,Yes
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,Yes
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,No
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,Yes
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,No
...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,Yes
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,No
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,No
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,No
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,Yes

In [58]:
datos2 = datos.drop(columns=["Despertares","Consumo cafeina"])

datos3 = datos2.dropna()

datos3

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

Si no me interesa perder datos, puedo eliminar todo lo que sea NA.

In [53]:
datos1.isna().sum()

ID                            0
Edad                          0
Género                        0
Hora dormir                   0
Hora despertar                0
Sleep duration                0
Sleep efficiency              0
Porcentaje suenio REM         0
Porcentaje suenio profundo    0
Porcentaje suenio liviano     0
Despertares                   0
Consumo cafeina               0
Consumo alcohol               0
Fumador                       0
Frecuencia ejercicio          0
dtype: int64

Tambien podria elegir no eliminar datos, sino reemplazarlos por valores, ej 0. Se lo llama "impitación de datos faltantes". Lo puedo hacer con .fillna().

In [82]:
datos3.fillna(0)

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

Otro valor valido para rellenar es la media --> .mean

In [83]:
datos3.fillna(datos.mean)

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

### 2.d. Eliminar datos duplicados

En muchos casos puede suceder que haya datos duplicados en nuestro dataset. ¿Se les ocurren ejemplos?

Para identificarlos, podemos usar duplicated(). ¿Qué está haciendo esta función?

In [84]:
datos3.duplicated().sum()

np.int64(7)

Quitar == .drop_duplicates()

In [85]:
datos3.drop_duplicates()

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,3.0,Yes,0.0
450,451,45,Male,2021-07-29 21:00:00,2021-07-29 04:00:00,7.0,0.76,18,72,10,0.0,No,3.0
451,452,18,Male,2021-03-17 02:30:00,2021-03-17 10:00:00,7.5,0.63,22,23,55,0.0,No,1.0
453,40,58,Female,2021-03-26 02:00:00,2021-03-26 09:00:00,7.0,0.63,22,23,55,3.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

In [86]:
datos3.drop_duplicates(keep = "last")

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

In [87]:
datos3["ID"].duplicated().sum()

np.int64(13)

Para solo sacar lo duplicados en referencia a "ID"

In [88]:
datos3.drop_duplicates(subset = "ID", keep = "last")

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

kepp = "last" es para q me deje la ultima instacia del duplicado.

### 2.e. Resetear el index

Una vez que eliminamos filas por el motivo que sea, nos van a quedar medio raros index. Veamos como nos quedó datos2

In [89]:
print(datos3.index)

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       451, 452, 453, 455, 456, 457, 458, 459, 460, 461],
      dtype='int64', length=441)

In [102]:
datos3.reset_index()

,index,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Consumo alcohol,Fumador,Frecuencia ejercicio
0,0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,0.0,Yes,2.0
437,458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,0.0,No,3.0
438,459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,1.0,No,3.0
439,460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
440,461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

### 3. Encadenar métodos

Esta forma de ir modificando un dataset no es muy práctica.

Por ejemplo si ejecutamos varias veces el mismo comando sin renombrar los datos, obtendremos cada vez algo distinto.

Si estamos creando un dataframe nuevo cada vez que hacemos algo, vamos a tener la memoria llena de objetos prácticamente iguales

Una solución es encadenar métodos para hacer el código más legible y fácil de reusar. Y más eficiente también.

Cada función genera un nuevo dataframe. Asi que siempre tengo que usar funciones que me generen un dataframe.

In [92]:
datos.drop(columns = ["Despertares","Consumo cafeina"]).dropna()

,ID,Edad,Género,Hora dormir,Hora despertar,Sleep duration,Sleep efficiency,Porcentaje suenio REM,Porcentaje suenio profundo,Porcentaje suenio liviano,Consumo alcohol,Fumador,Frecuencia ejercicio
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

#### Extra: pipes
Una cadena de operaciones encadenadas suele llamarse un "pipe" (tubería). 

Por ejemplo, en R podemos hacer pipes en un DataFrame con %>%:

`first(x) %>% second(x) %>% third(x)`

En Python podemos encadenar métodos directamente poniendo uno a continuación del otro, por lo tanto en general no necesitamos un comando especial para pipes. 

Igualmente, los DataFrames de Pandas también tienen un método `pipe()` para encadenar funciones aplicadas al DataFrame que puede resultar útil.